[package]
name = "leetcode01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="0001"
path="src/0001_two_sum/bin/main.rs"

[[bin]]
name="0509"
path="src/0509_fibonacci/bin/main.rs"

[dependencies]
